### PR TITLE
Adding inital styling for page

### PR DESCRIPTION
**Pull request by Brallen**
This has the initial styles for the page. I also added in some shapes to the canvas to get an idea of how the layout will be.

### CODE REVIEW

**Comment by CubePresser** [comment]
I think it would be best if we instead created the layout via HTML and CSS rather than putting shapes into the canvas. Leaving the canvas purely for rendering the playing field. Unless this is what you were planning to do and had really only put in the shapes just to see how the layout looked 👍

**Comment by Brallen** [comment]
This opens up a good question. Is there a way for us to get information outside of the canvas? Things like the score and what color is next needs to be tied to the game somehow. This might be a good question for Noah on if he knows if the createJS can update DOM elements outside the canvas element

**Comment by CubePresser** [comment]
From what I understand, we provide information to the canvas. All the canvas does is render in what information we give it for every frame. So data like, shapes, score and what color is next will already be stored outside of the canvas, easily accessible for any DOM element.

**Comment by Brallen** [comment]
That makes sense. Let me do a little bit more digging and then see if any changes need to be made to support this

**Comment by Manason** [comment]
We can have multiple canvases, but one canvas should just be the game board, and nothing extra.

**Comment by Brallen** [comment]
Merging this PR and will make color section a stage in issue  [#15](https://github.com/Brallen/ColorGame/issues/15)

**Pull request merged**
